# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dce2af8435cd940a9ee854f72cfa4cf38ae522e073a9bb914bb3b85b9d6857df38d72ef565acc38fb18ee4ee57dabe296a14c6a7ce7354ef786be452cf061e58

test:
  secret_key_base: 754d045f31aedc477f2b4d502a6e2b7a5147a6d8d5f1b987a4df09c9671c0af9aec37f75324b5d8387d2284c57386b24409dfd48d59b6ed5beea0eb7a7e12b4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
